find_program(CLANG_TIDY_EXE NAMES "clang-tidy" DOC "Path to clang-tidy executable")
if (NOT CLANG_TIDY_EXE)
    message(FATAL_ERROR "clang-tidy not found.")
else ()
    message(STATUS "clang-tidy found: ${CLANG_TIDY_EXE}")
    set(DO_CLANG_TIDY "${CLANG_TIDY_EXE}" "-checks=-*,modernize-*,-modernize-avoid-bind,-modernize-use-trailing-return-type,cppcoreguidelines-*,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,clang-analyzer-*,bugprone-*" "-warnings-as-errors=*")
endif ()