name: game_of_life CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'tools/Dockerfile'
      volumes:
      - /workspace:/github/workspace
    steps:
      - uses: actions/checkout@v2

      - name: Make
        run: pwd && ls -l && mkdir build && cd build && cmake .. && make -j8
      
#       - name: Build and tag image
#         run: docker build -t "docker:latest" -f tools/Dockerfile .
      
#       - name: Run image
#         run: docker run -it -d --name builder -v $GITHUB_WORKSPACE:/workspace -w /workspace docker:latest
      
#       - name: Make
#         run: docker exec builder bash -c 'pwd && ls -l && mkdir build && cd build && cmake .. && make -j8'
      
      - name: Save artifact
        run: docker exec builder bash -c 'cp -r build output'
      - uses: actions/upload-artifact@master
        with:
          name: firmware-${{ env.FIRMWARE_VERSION }}
          path: output
  
#   test:
#     runs-on: ubuntu-latest
#     needs: build
  
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/download-artifact@master
#       with:
#         name: firmware-${{ env.FIRMWARE_VERSION }}
#         path: output
#     - name: test
#       run: docker exec builder bash -c 'cp -r build output'
